EsuException: error code is now splited between HttpCode (HTTP result code) and AtmosCode (detailed internal Atmos error) EsuException: warning the interface has changed, getCode() is no longer available EsuRestApi: corrected signRequest() to allow Url escaped characters DownloadHelper: Atmos bug turn-around for Url escaped characters
git-svn-id: https://atmos-java.googlecode.com/svn/trunk/@8 f9042120-e4f6-11de-b362-3513cf04e977